version: "3.9"
services:

  ln-utils-bot:
    container_name: ln-utils-bot
    image: ln-utils-bot:latest
    depends_on: [lnd]
    restart: on-failure
    environment:
      - TELOXIDE_TOKEN=token
      - CERT_PATH=your_cert_hex
      - MACAROON_PATH=your_macaroon_hex
      - SOCKET=lnd:10009

networks:
  default:
    name: lnd_network
    external: true
